apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver-deploy
  name: webserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: webserver-deploy
    spec:
      containers:
      - image: {{ .Values.webserver_image }}
        name: webserver
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: server-config

        # env:
        #   - name: MYSQL_DATABASE_HOST
        #     value: mysql
        #   - name: MYSQL_PASSWORD
        #     value: Clarusway_1
        #   - name: MYSQL_USER
        #     value: Clarus 
        #   - name: MYSQL_DATABASE
        #     value: phonebook
        resources: {}

